# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push

env:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  MAVEN_CLI_OPTS: --strict-checksums --threads 4C --batch-mode

jobs:
  build:
    runs-on: ubuntu-latest        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '17'
          maven-version: '3.8.5'
      - name: Build with Maven
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkstyle
        run: mvn -e $MAVEN_CLI_OPTS $MAVEN_OPTS org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle > checkstyle-result.xml
        if: ${{ job.status == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-result.xml
          path: target/checkstyle-result.xml
      - name: Spotbugs
        run:  mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile com.github.spotbugs:spotbugs-maven-plugin:4.0.4:spotbugs > spotbugs-result.xml
        if: ${{ job.status == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-result.xml
          path: target/spotbugs-result.xml
