# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push

env:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--strict-checksums --threads 4C --batch-mode"

jobs:

  build:
    runs-on: ubuntu-latest        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '8'
          maven-version: '3.8.3'
      - name: Build with Maven
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile
  Checkstyle:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '8'
          maven-version: '3.8.3'
      - name: Checkstyle
        run: mvn -e $MAVEN_CLI_OPTS $MAVEN_OPTS org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle
      - name: Checkstyle-artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-result.xml
          path: target/checkstyle-result.xml
  Spotbugs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '8'
          maven-version: '3.8.3'
      - name: Spotbugs
        run:  mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile com.github.spotbugs:spotbugs-maven-plugin:4.0.4:spotbugs
      - name: Spotbugs-artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-result.xml
          path: target/spotbugs-result.xml
  Tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '17'
          maven-version: '3.8.3'
      - name: Test
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS test
      - name: Shield.io
        run: echo "TODO"
  Package:
    runs-on: ubuntu-latest
    needs: Tests
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '17'
          maven-version: '3.8.3'
      - name: Package
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS -D skipTests clean package
      - name: Create Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: UninaTestPipeline-1.0-SNAPSHOT.jar
          path: target/*.jar
