name: Java CI with Maven

on:
  push
# release:
#   types: [published]
#Workflows are not triggered for the created, edited, or deleted activity types for draft releases.
#When you create your release through the GitHub browser UI, your release may automatically be saved as a draft.

env:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--strict-checksums --threads 4C --batch-mode"

  NumberOfTest: 0
  TestResult: failed
  UnitTestResult: failed
  IntegrationTestResult: failed
  NumberOfUnitTest: 0
  NumberOfIntegrationTest: 0
  UnitTestFailed: 0
  IntegrationTestFailed: 0

jobs:

  build:
    runs-on: ubuntu-latest        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '8'
          maven-version: '3.8.3'
      - name: Build with Maven
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile
      - name: Script-artifact
        uses: actions/upload-artifact@v3
        with:
          name: derivateResult.sh
          path: .github/derivateResult.sh
  Checkstyle:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '8'
          maven-version: '3.8.3'
      - name: Checkstyle
        run: mvn -e $MAVEN_CLI_OPTS $MAVEN_OPTS org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle
      - name: Checkstyle-artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-result.xml
          path: target/checkstyle-result.xml
  Spotbugs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '8'
          maven-version: '3.8.3'
      - name: Spotbugs
        run:  mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile com.github.spotbugs:spotbugs-maven-plugin:4.0.4:spotbugs
      - name: Spotbugs-artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-result.xml
          path: target/spotbugs-result.xml
  Tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '17'
          maven-version: '3.8.3'
      - name: Unit Test
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS test -P unit-test
      - name: Integration Test
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS test -P integration-test
      - name: Create Unit Test Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Report
          path: target/surefire-reports/*unit*.txt
      - name: Create Integration Test Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Integration Test Report
          path: target/surefire-reports/*integration*.txt
  Package:
    runs-on: ubuntu-latest
    needs: Tests
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '17'
          maven-version: '3.8.3'
      - name: Package
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS -D skipTests clean package
      - name: Create Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: UninaTestPipeline-1.0-SNAPSHOT.jar
          path: target/*.jar
  RetrieveTestResults:
    runs-on: ubuntu-latest
    needs: Tests
    outputs:
      test-result: ${{ steps.set_outputs.outputs.test-result }}
      number-of-test: ${{ steps.set_outputs.outputs.number-of-test }}
      unit-test-result: ${{ steps.set_outputs.outputs.unit-test-result }}
      integration-test-result: ${{ steps.set_outputs.outputs.integration-test-result }}
      number-of-unit-test: ${{ steps.set_outputs.outputs.number-of-unit-test }}
      number-of-integration-test: ${{ steps.set_outputs.outputs.number-of-integration-test }}
      unit-test-failed: ${{ steps.set_outputs.outputs.unit-test-failed }}
      integration-test-failed: ${{ steps.set_outputs.outputs.integration-test-failed }}
    steps:
      - name: Download Integration Test Report
        uses: actions/download-artifact@v3
        with:
          name: Integration Test Report
      - name: Download Unit Test Report
        uses: actions/download-artifact@v3
        with:
          name: Unit Test Report
      - name: Download Script derivateResult
        uses: actions/download-artifact@v3
        with:
          name: derivateResult.sh
      - name: Retrieve number of integration and unit test
        run: |
          echo "NumberOfIntegrationTest=$(grep -o -w "Tests run: [0-9]*" *integration*.txt | cut -d' ' -f 3)" >> $GITHUB_ENV
          echo "NumberOfUnitTest=$(grep -o -w "Tests run: [0-9]*" *unit*.txt | cut -d' ' -f 3)" >> $GITHUB_ENV
          echo "UnitTestFailed=$(grep -o -w "Failures: [0-9]*" *unit*.txt | cut -d' ' -f 2)" >> $GITHUB_ENV
          echo "IntegrationTestFailed=$(grep -o -w "Failures: [0-9]*" *integration*.txt | cut -d' ' -f 2)" >> $GITHUB_ENV
      - name: Calculate Total Number Of Tests
        run: |
          echo "NumberOfTest=$(($NumberOfIntegrationTest + $NumberOfUnitTest))" >> $GITHUB_ENV
      - name: Retrieve Tests result
        run: |
           echo "UnitTestResult=$(bash derivateResult.sh $UnitTestFailed)" >> $GITHUB_ENV
           echo "IntegrationTestResult=$(bash derivateResult.sh $IntegrationTestFailed)" >> $GITHUB_ENV
           echo "TestResult=$(bash derivateResult.sh $UnitTestFailed $IntegrationTestFailed)" >> $GITHUB_ENV
      - name: Set Output Values
        id: set_outputs
        run: |
          echo "::set-output name=test-result::$TestResult"
          echo "::set-output name=number-of-test::$NumberOfTest"
          echo "::set-output name=unit-test-result::$UnitTestResult"
          echo "::set-output name=integration-test-result::$IntegrationTestResult"
          echo "::set-output name=number-of-unit-test::$NumberOfUnitTest"
          echo "::set-output name=number-of-integration-test::$NumberOfIntegrationTest"

  CreateBadges:
     runs-on: ubuntu-latest
     needs: RetrieveTestResults
     steps:
      - name: Configure Job Eviroment
        run: |
          mkdir -p .github/badges/test_result.svg
          mkdir -p .github/badges/test_number.svg
          mkdir -p .github/badges/unit_test_number.svg
          mkdir -p .github/badges/integration_test_number.svg
          mkdir -p .github/badges/unit_test_result.svg
          mkdir -p .github/badges/integration_test_result.svg
          echo "::set-env name=TestResult::${{ needs.RetrieveTestResults.outputs.test-result }}"
          echo "::set-env name=NumberOfTest::${{ needs.RetrieveTestResults.outputs.number-of-test }}"
          echo "::set-env name=UnitTestResult::${{ needs.RetrieveTestResults.outputs.unit-test-result }}"
          echo "::set-env name=IntegrationTestResult::${{ needs.RetrieveTestResults.outputs.integration-test-result }}"
          echo "::set-env name=NumberOfUnitTest::${{ needs.RetrieveTestResults.outputs.number-of-unit-test }}"
          echo "::set-env name=NumberOfIntegrationTest::${{ needs.RetrieveTestResults.outputs.number-of-integration-test }}"
      - name: CreateBadge Test Result
        uses: emibcn/badge-action@v1.2.1
        with:
          label: Test Result
          status: ${ { env.TestResult } }
          color: ${{
            env.TestResult == Failed && 'green'     ||
            env.TestResult == Passed && 'red'       ||
            } }
          path: .github/badges/test_result.svg
      - name: CreateBadge Test Number
        uses: emibcn/badge-action@v1.2.1
        with:
          label: Number Of Test
          status: ${ { env.NumberOfTest } }
          color: blue
          path: .github/badges/test_number.svg
      - name: CreateBadge Unit Test Result
        uses: emibcn/badge-action@v1.2.1
        with:
          label: Unit Test Result
          status: ${ { env.UnitTestResult } }
          color: ${{
            env.UnitTestResult == Failed && 'green'     ||
            env.UnitTestResult == Passed && 'red'       ||
            } }
          path: .github/badges/unit_test_result.svg
      - name: CreateBadge Integration Test Result
        uses: emibcn/badge-action@v1.2.1
        with:
          label: Integration Test Result
          status: ${ { env.IntegrationTestResult } }
          color: ${{
            env.IntegrationTestResult == Failed && 'green'     ||
            env.IntegrationTestResult == Passed && 'red'       ||
            } }
          path: .github/badges/integration_test_result.svg
      - name: CreateBadge Integration Test Number
        uses: emibcn/badge-action@v1.2.1
        with:
          label: Integration Test Number
          status: ${ { env.NumberOfIntegrationTest } }
          color: blue
          path: .github/badges/integration_test_number.svg
      - name: CreateBadge Unit Test Number
        uses: emibcn/badge-action@v1.2.1
        with:
          label: Unit Test Number
          status: ${ { env.NumberOfUnitTest } }
          color: blue
          path: .github/badges/unit_test_number.svg
      - name: Create Badge Folder Artifact
        uses: actions/upload-artifact@v3
        with:
          name: badges
          path: .github/badges/

